### ISSUE TITLE
A question about disparity

### ISSUE THREAD

**Issue by pyni** [junyang224/ROBI_Toolkit#2]
Hi~ I notice the following in your code:
pix_right_x = pix_left_x + disparity

So how about the relationship between pix_right_y and pix_left_y?

**Comment by junyang224** [comment]
Hello:

Thanks for your interest in ROBI dataset.

I believe you are asking the code in file "read_pattern_imgs.py", which is used to use the pattern projected stereo pair.

Since the depth camera is the stereo camera, and the stereo pair is the rectified left and right image. For each correspondence, there will be three variables :
"pix_left_x":  pixel X coordinate in left image
"pix_right_x":  pixel X coordinate in right image
"pix_y":  pixel Y coordinate in left and right image

The difference between "pix_left_x" and "pix_right_x" is the disparity, and the code "pix_right_x = pix_left_x + disparity" implies the following correspondence:
                    left_pattern_img[pix_y, pix_left_x] -> right_pattern_img[pix_y, pix_right_x ]
                    left_pattern_img[pix_y, pix_left_x] -> right_pattern_img[pix_y, pix_left_x + disparity]

Let me know if this is clear to you.
Jun

**Comment by pyni** [comment]
OK,I got it.
Thanks for your work.
