### ISSUE TITLE
question

### ISSUE THREAD

**Issue by xumingkun9806** [junyang224/ROBI_Toolkit#3]
Thanks for your dataset.I have three quetion.
1.In test/Ensenso_LEFT.yml cx: 379.326874 that’s right？In test/Ensenso_DEPTH.yml  depth_unit: 0.03125 that‘s in mm？cv2.imread(DEPTH_path, cv2.IMREAD_ANYDEPTH) * depth_unit get the true depth and in mm
2.read_pattern_imgs.py what task is it used for？
3.the cam_pose is the pose from world to cam?the GT picture is  processed by you and that's better than origin?

**Comment by junyang224** [comment]
Hello:

Please find my answer below:
In test/Ensenso_LEFT.yml cx: 379.326874 that’s right？
-> yes, the cx is 379.326874 for Ensenso_left. Please note that, the cx is different for Ensenso_left and Ensenso_right.

In test/Ensenso_DEPTH.yml depth_unit: 0.03125 that‘s in mm？
-> The depth unit will be applied when you using the depth image. The actual depth value for a pixel is the read value multiplied by the depth unit. **The final unit is mm**. 

read_pattern_imgs.py what task is it used for？
-> The "read_pattern_imgs.py" is mainly used for the depth/disparity estimation. Since Ensenso and RealSense Camera are the active stereo camera, we therefore provide the pattern projected image. Researchers are welcome to develop their own algorithms to estimate the depth instead of using the captured depth data

the cam_pose is the pose from world to cam?
->THE cam_pose is the pose of the camera relative to the world coordinate.

the GT picture is processed by you and that's better than origin?
->Not sure if I understand this questions correctly...… We captured the GT depth image using scanning spray and Ensenso camera, which is at least one grade better than original captures (with shiny surfaces)\

Let me know if you have more questions
Jun

**Comment by xumingkun9806** [comment]
Thanks for your quick answer！！I understand.
